In [232]:
!pip install -r requirements.txt
!pip install kagglehub

Requirement already satisfied: altair==5.5.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (5.5.0)
Requirement already satisfied: attrs==25.1.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (25.1.0)
Requirement already satisfied: blinker==1.9.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (1.9.0)
Requirement already satisfied: cachetools==5.5.1 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (5.5.1)
Requirement already satisfied: certifi==2025.1.31 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (2025.1.31)
Requirement already satisfied: charset-normalizer==3.4.1 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 6)) (3.4.1)
Requirement already satisfied: click==8.1.8 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 7)) (8.1.8)
Requirement already satisfied: colorama==0.4.6 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 8)) (0.4.6)
Requirement already satisfied: gitdb==4.0.12 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 9)) (4.0.12)
Requirement already satisfied: GitPython==3.1.44 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 10)) (3.1.44)
Requirement already satisfied: idna==3.10 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 11)) (3.10)
Requirement already satisfied: Jinja2==3.1.5 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 12)) (3.1.5)
Requirement already satisfied: joblib==1.4.2 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 13)) (1.4.2)
Requirement already satisfied: jsonschema==4.23.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 14)) (4.23.0)
Requirement already satisfied: jsonschema-specifications==2024.10.1 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 15)) (2024.10.1)
Requirement already satisfied: markdown-it-py==3.0.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 16)) (3.0.0)
Requirement already satisfied: MarkupSafe==3.0.2 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 17)) (3.0.2)
Requirement already satisfied: mdurl==0.1.2 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 18)) (0.1.2)
Requirement already satisfied: narwhals==1.26.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 19)) (1.26.0)
Requirement already satisfied: numpy==2.2.2 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 20)) (2.2.2)
Requirement already satisfied: packaging==24.2 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 21)) (24.2)
Requirement already satisfied: pandas==2.2.3 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 22)) (2.2.3)
Requirement already satisfied: pillow==11.1.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 23)) (11.1.0)
Requirement already satisfied: protobuf==5.29.3 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 24)) (5.29.3)
Requirement already satisfied: pyarrow==19.0.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 25)) (19.0.0)
Requirement already satisfied: pydeck==0.9.1 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 26)) (0.9.1)
Requirement already satisfied: Pygments==2.19.1 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 27)) (2.19.1)
Requirement already satisfied: python-dateutil==2.9.0.post0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 28)) (2.9.0.post0)
Requirement already satisfied: pytz==2025.1 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 29)) (2025.1)
Requirement already satisfied: referencing==0.36.2 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 30)) (0.36.2)
Requirement already satisfied: requests==2.32.3 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 31)) (2.32.3)
Requirement already satisfied: rich==13.9.4 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 32)) (13.9.4)
Requirement already satisfied: rpds-py==0.22.3 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 33)) (0.22.3)
Requirement already satisfied: scikit-learn==1.6.1 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 34)) (1.6.1)
Requirement already satisfied: scipy==1.15.1 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 35)) (1.15.1)
Requirement already satisfied: six==1.17.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 36)) (1.17.0)
Requirement already satisfied: smmap==5.0.2 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 37)) (5.0.2)
Requirement already satisfied: streamlit==1.42.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 38)) (1.42.0)
Requirement already satisfied: tenacity==9.0.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 39)) (9.0.0)
Requirement already satisfied: threadpoolctl==3.5.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 40)) (3.5.0)
Requirement already satisfied: toml==0.10.2 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 41)) (0.10.2)
Requirement already satisfied: tornado==6.4.2 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 42)) (6.4.2)
Requirement already satisfied: typing_extensions==4.12.2 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 43)) (4.12.2)
Requirement already satisfied: tzdata==2025.1 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 44)) (2025.1)
Requirement already satisfied: urllib3==2.3.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 45)) (2.3.0)
Requirement already satisfied: watchdog==6.0.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 46)) (6.0.0)
Requirement already satisfied: xgboost==2.1.4 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 47)) (2.1.4)
Requirement already satisfied: nvidia-nccl-cu12 in ./venv/lib/python3.12/site-packages (from xgboost==2.1.4->-r requirements.txt (line 47)) (2.29.7)
Requirement already satisfied: kagglehub in ./venv/lib/python3.12/site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in ./venv/lib/python3.12/site-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in ./venv/lib/python3.12/site-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in ./venv/lib/python3.12/site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in ./venv/lib/python3.12/site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in ./venv/lib/python3.12/site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in ./venv/lib/python3.12/site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.3)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.12/site-packages (from requests->kagglehub) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.12/site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.12/site-packages (from requests->kagglehub) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.12/site-packages (from requests->kagglehub) (2025.1.31)

In [233]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("dgsports/ipl-ball-by-ball-2008-to-2022")

print("Path to dataset files:", path)

Path to dataset files: /home/tst_imperial/.cache/kagglehub/datasets/dgsports/ipl-ball-by-ball-2008-to-2022/versions/5

In [234]:
import pandas as pd

In [235]:
ini_df = pd.read_csv("deliveries_updated_ipl_upto_2025.csv")

In [236]:
ini_df.columns

Index(['matchId', 'inning', 'over_ball', 'over', 'ball', 'batting_team',
       'bowling_team', 'batsman', 'non_striker', 'bowler', 'batsman_runs',
       'extras', 'isWide', 'isNoBall', 'Byes', 'LegByes', 'Penalty',
       'dismissal_kind', 'player_dismissed', 'date'],
      dtype='object')

In [237]:
df = ini_df[["matchId","inning","over_ball","over","ball","batting_team","bowling_team","batsman_runs","extras","date","player_dismissed"]]

In [238]:
df

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman_runs,extras,date,player_dismissed
0,335982,1,0.1,0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,2008-04-18,NaN
1,335982,1,0.2,0,2,Kolkata Knight Riders,Royal Challengers Bangalore,0,0,2008-04-18,NaN
2,335982,1,0.3,0,3,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,2008-04-18,NaN
3,335982,1,0.4,0,4,Kolkata Knight Riders,Royal Challengers Bangalore,0,0,2008-04-18,NaN
4,335982,1,0.5,0,5,Kolkata Knight Riders,Royal Challengers Bangalore,0,0,2008-04-18,NaN
...,...,...,...,...,...,...,...,...,...,...,...
278200,1473511,2,19.2,19,2,Punjab Kings,Royal Challengers Bengaluru,0,0,2025-06-03,NaN
278201,1473511,2,19.3,19,3,Punjab Kings,Royal Challengers Bengaluru,6,0,2025-06-03,NaN
278202,1473511,2,19.4,19,4,Punjab Kings,Royal Challengers Bengaluru,4,0,2025-06-03,NaN
278203,1473511,2,19.5,19,5,Punjab Kings,Royal Challengers Bengaluru,6,0,2025-06-03,NaN
278204,1473511,2,19.6,19,6,Punjab Kings,Royal Challengers Bengaluru,6,0,2025-06-03,NaN

In [239]:
df["date"]=pd.to_datetime(df["date"])

/tmp/ipykernel_13762/1303019909.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date"]=pd.to_datetime(df["date"])

In [240]:
df["date"]

0        2008-04-18
1        2008-04-18
2        2008-04-18
3        2008-04-18
4        2008-04-18
            ...
278200   2025-06-03
278201   2025-06-03
278202   2025-06-03
278203   2025-06-03
278204   2025-06-03
Name: date, Length: 278205, dtype: datetime64[ns]

In [241]:
df = df[df["date"]>="2024-01-01"]

In [242]:
df

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman_runs,extras,date,player_dismissed
243817,1422119,1,0.1,0,1,Royal Challengers Bengaluru,Chennai Super Kings,0,1,2024-03-22,NaN
243818,1422119,1,0.2,0,2,Royal Challengers Bengaluru,Chennai Super Kings,1,0,2024-03-22,NaN
243819,1422119,1,0.3,0,3,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN
243820,1422119,1,0.4,0,4,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN
243821,1422119,1,0.5,0,5,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN
...,...,...,...,...,...,...,...,...,...,...,...
278200,1473511,2,19.2,19,2,Punjab Kings,Royal Challengers Bengaluru,0,0,2025-06-03,NaN
278201,1473511,2,19.3,19,3,Punjab Kings,Royal Challengers Bengaluru,6,0,2025-06-03,NaN
278202,1473511,2,19.4,19,4,Punjab Kings,Royal Challengers Bengaluru,4,0,2025-06-03,NaN
278203,1473511,2,19.5,19,5,Punjab Kings,Royal Challengers Bengaluru,6,0,2025-06-03,NaN
278204,1473511,2,19.6,19,6,Punjab Kings,Royal Challengers Bengaluru,6,0,2025-06-03,NaN

In [243]:
df = df.reset_index()

In [244]:
df

,index,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman_runs,extras,date,player_dismissed
0,243817,1422119,1,0.1,0,1,Royal Challengers Bengaluru,Chennai Super Kings,0,1,2024-03-22,NaN
1,243818,1422119,1,0.2,0,2,Royal Challengers Bengaluru,Chennai Super Kings,1,0,2024-03-22,NaN
2,243819,1422119,1,0.3,0,3,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN
3,243820,1422119,1,0.4,0,4,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN
4,243821,1422119,1,0.5,0,5,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
34383,278200,1473511,2,19.2,19,2,Punjab Kings,Royal Challengers Bengaluru,0,0,2025-06-03,NaN
34384,278201,1473511,2,19.3,19,3,Punjab Kings,Royal Challengers Bengaluru,6,0,2025-06-03,NaN
34385,278202,1473511,2,19.4,19,4,Punjab Kings,Royal Challengers Bengaluru,4,0,2025-06-03,NaN
34386,278203,1473511,2,19.5,19,5,Punjab Kings,Royal Challengers Bengaluru,6,0,2025-06-03,NaN
34387,278204,1473511,2,19.6,19,6,Punjab Kings,Royal Challengers Bengaluru,6,0,2025-06-03,NaN

In [245]:
df["runs_scored"]=df["batsman_runs"]+df["extras"]

In [246]:
df

,index,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman_runs,extras,date,player_dismissed,runs_scored
0,243817,1422119,1,0.1,0,1,Royal Challengers Bengaluru,Chennai Super Kings,0,1,2024-03-22,NaN,1
1,243818,1422119,1,0.2,0,2,Royal Challengers Bengaluru,Chennai Super Kings,1,0,2024-03-22,NaN,1
2,243819,1422119,1,0.3,0,3,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN,0
3,243820,1422119,1,0.4,0,4,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN,0
4,243821,1422119,1,0.5,0,5,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34383,278200,1473511,2,19.2,19,2,Punjab Kings,Royal Challengers Bengaluru,0,0,2025-06-03,NaN,0
34384,278201,1473511,2,19.3,19,3,Punjab Kings,Royal Challengers Bengaluru,6,0,2025-06-03,NaN,6
34385,278202,1473511,2,19.4,19,4,Punjab Kings,Royal Challengers Bengaluru,4,0,2025-06-03,NaN,4
34386,278203,1473511,2,19.5,19,5,Punjab Kings,Royal Challengers Bengaluru,6,0,2025-06-03,NaN,6
34387,278204,1473511,2,19.6,19,6,Punjab Kings,Royal Challengers Bengaluru,6,0,2025-06-03,NaN,6

In [247]:
df.describe()

,index,matchId,inning,over_ball,over,ball,batsman_runs,extras,date,runs_scored
count,34388.000000,3.438800e+04,34388.000000,34388.000000,34388.000000,34388.000000,34388.000000,34388.000000,34388,34388.000000
mean,261010.500000,1.449471e+06,1.476794,9.547491,9.181720,3.658573,1.453007,0.073630,2024-10-21 23:23:36.633709312,1.526637
min,243817.000000,1.422119e+06,1.000000,0.100000,0.000000,1.000000,0.000000,0.000000,2024-03-22 00:00:00,0.000000
25%,252413.750000,1.426274e+06,1.000000,4.500000,4.000000,2.000000,0.000000,0.000000,2024-04-21 00:00:00,0.000000
50%,261010.500000,1.473438e+06,1.000000,9.400000,9.000000,4.000000,1.000000,0.000000,2025-03-22 00:00:00,1.000000
75%,269607.250000,1.473474e+06,2.000000,14.400000,14.000000,5.000000,2.000000,0.000000,2025-04-20 00:00:00,2.000000
max,278204.000000,1.485779e+06,4.000000,19.900000,19.000000,11.000000,6.000000,5.000000,2025-06-03 00:00:00,7.000000
std,9927.104865,2.436851e+04,0.500515,5.669495,5.664169,1.845284,1.804689,0.350297,NaN,1.782880

In [248]:
df[30:46]

,index,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman_runs,extras,date,player_dismissed,runs_scored
30,243847,1422119,1,4.5,4,5,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN,0
31,243848,1422119,1,4.6,4,6,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,RM Patidar,0
32,243849,1422119,1,5.1,5,1,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN,0
33,243850,1422119,1,5.2,5,2,Royal Challengers Bengaluru,Chennai Super Kings,1,0,2024-03-22,NaN,1
34,243851,1422119,1,5.3,5,3,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,GJ Maxwell,0
35,243852,1422119,1,5.4,5,4,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN,0
36,243853,1422119,1,5.5,5,5,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN,0
37,243854,1422119,1,5.6,5,6,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN,0
38,243855,1422119,1,6.1,6,1,Royal Challengers Bengaluru,Chennai Super Kings,1,0,2024-03-22,NaN,1
39,243856,1422119,1,6.2,6,2,Royal Challengers Bengaluru,Chennai Super Kings,2,0,2024-03-22,NaN,2
40,243857,1422119,1,6.3,6,3,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN,0
41,243858,1422119,1,6.4,6,4,Royal Challengers Bengaluru,Chennai Super Kings,1,0,2024-03-22,NaN,1
42,243859,1422119,1,6.5,6,5,Royal Challengers Bengaluru,Chennai Super Kings,1,0,2024-03-22,NaN,1
43,243860,1422119,1,6.6,6,6,Royal Challengers Bengaluru,Chennai Super Kings,1,0,2024-03-22,NaN,1
44,243861,1422119,1,7.1,7,1,Royal Challengers Bengaluru,Chennai Super Kings,0,0,2024-03-22,NaN,0
45,243862,1422119,1,7.2,7,2,Royal Challengers Bengaluru,Chennai Super Kings,1,0,2024-03-22,NaN,1

In [249]:
df=df.drop(["batsman_runs","extras"],axis=1)

In [250]:
df['is_wicket'] = df['player_dismissed'].notna().astype(int)
df['wickets_lost'] = df.groupby(['date', 'inning'])['is_wicket'].cumsum()
df['wickets_remaining'] = 10 - df['wickets_lost']
df.drop(columns=['is_wicket', 'wickets_lost',"index"], inplace=True)

In [251]:
df

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,date,player_dismissed,runs_scored,wickets_remaining
0,1422119,1,0.1,0,1,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,NaN,1,10
1,1422119,1,0.2,0,2,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,NaN,1,10
2,1422119,1,0.3,0,3,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,NaN,0,10
3,1422119,1,0.4,0,4,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,NaN,0,10
4,1422119,1,0.5,0,5,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,NaN,0,10
...,...,...,...,...,...,...,...,...,...,...,...
34383,1473511,2,19.2,19,2,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,NaN,0,3
34384,1473511,2,19.3,19,3,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,NaN,6,3
34385,1473511,2,19.4,19,4,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,NaN,4,3
34386,1473511,2,19.5,19,5,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,NaN,6,3
34387,1473511,2,19.6,19,6,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,NaN,6,3

In [252]:
df["score"]=0
df["runs_scored"] = df["runs_scored"].astype(float)
final_scores = df.groupby(["matchId", "batting_team"])["runs_scored"].sum().reset_index()
final_scores.rename(columns={"runs_scored": "final_score"}, inplace=True)
df = df.merge(final_scores, on=["matchId", "batting_team"], how="left")
df

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,date,player_dismissed,runs_scored,wickets_remaining,score,final_score
0,1422119,1,0.1,0,1,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,NaN,1.0,10,0,173.0
1,1422119,1,0.2,0,2,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,NaN,1.0,10,0,173.0
2,1422119,1,0.3,0,3,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,NaN,0.0,10,0,173.0
3,1422119,1,0.4,0,4,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,NaN,0.0,10,0,173.0
4,1422119,1,0.5,0,5,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,NaN,0.0,10,0,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34383,1473511,2,19.2,19,2,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,NaN,0.0,3,0,184.0
34384,1473511,2,19.3,19,3,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,NaN,6.0,3,0,184.0
34385,1473511,2,19.4,19,4,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,NaN,4.0,3,0,184.0
34386,1473511,2,19.5,19,5,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,NaN,6.0,3,0,184.0
34387,1473511,2,19.6,19,6,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,NaN,6.0,3,0,184.0

In [253]:
df=df.drop(["player_dismissed"],axis=1)

In [254]:
def update_running_score(df):
    df["score"] = 0 
    for (match, innings), group in df.groupby(["matchId", "inning"]):
        total_score = 0 
        for idx in group.index:
            total_score += df.at[idx, "runs_scored"]
            df.at[idx, "score"] = total_score  

    return df

In [255]:
df = update_running_score(df)

In [256]:
df

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,date,runs_scored,wickets_remaining,score,final_score
0,1422119,1,0.1,0,1,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,1.0,10,1,173.0
1,1422119,1,0.2,0,2,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,1.0,10,2,173.0
2,1422119,1,0.3,0,3,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,0.0,10,2,173.0
3,1422119,1,0.4,0,4,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,0.0,10,2,173.0
4,1422119,1,0.5,0,5,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,0.0,10,2,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...
34383,1473511,2,19.2,19,2,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,0.0,3,162,184.0
34384,1473511,2,19.3,19,3,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,6.0,3,168,184.0
34385,1473511,2,19.4,19,4,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,4.0,3,172,184.0
34386,1473511,2,19.5,19,5,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,6.0,3,178,184.0
34387,1473511,2,19.6,19,6,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,6.0,3,184,184.0

In [257]:
import pandas as pd
import requests
import zipfile
import io
import json

print("Downloading IPL match metadata from Cricsheet...")
url = "https://cricsheet.org/downloads/ipl_json.zip"
headers = {'User-Agent': 'Mozilla/5.0'}

# Download and unzip the files entirely in memory
response = requests.get(url, headers=headers)
z = zipfile.ZipFile(io.BytesIO(response.content))

match_data = []

for filename in z.namelist():
    if filename.endswith(".json") and filename != "README.txt":
        with z.open(filename) as f:
            data = json.load(f)

            match_id = int(filename.split('.')[0])

            venue = data.get('info', {}).get('venue', 'Unknown')
            
            match_data.append({'matchId': match_id, 'venue': venue})

matches_df = pd.DataFrame(match_data)


df = pd.merge(df, matches_df, on='matchId', how='left')

print(f"Missing venues after merge: {df['venue'].isnull().sum()}")

Downloading IPL match metadata from Cricsheet...
Missing venues after merge: 0

In [258]:
df

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,date,runs_scored,wickets_remaining,score,final_score,venue
0,1422119,1,0.1,0,1,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,1.0,10,1,173.0,"MA Chidambaram Stadium, Chepauk, Chennai"
1,1422119,1,0.2,0,2,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,1.0,10,2,173.0,"MA Chidambaram Stadium, Chepauk, Chennai"
2,1422119,1,0.3,0,3,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,0.0,10,2,173.0,"MA Chidambaram Stadium, Chepauk, Chennai"
3,1422119,1,0.4,0,4,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,0.0,10,2,173.0,"MA Chidambaram Stadium, Chepauk, Chennai"
4,1422119,1,0.5,0,5,Royal Challengers Bengaluru,Chennai Super Kings,2024-03-22,0.0,10,2,173.0,"MA Chidambaram Stadium, Chepauk, Chennai"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34383,1473511,2,19.2,19,2,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,0.0,3,162,184.0,"Narendra Modi Stadium, Ahmedabad"
34384,1473511,2,19.3,19,3,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,6.0,3,168,184.0,"Narendra Modi Stadium, Ahmedabad"
34385,1473511,2,19.4,19,4,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,4.0,3,172,184.0,"Narendra Modi Stadium, Ahmedabad"
34386,1473511,2,19.5,19,5,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,6.0,3,178,184.0,"Narendra Modi Stadium, Ahmedabad"
34387,1473511,2,19.6,19,6,Punjab Kings,Royal Challengers Bengaluru,2025-06-03,6.0,3,184,184.0,"Narendra Modi Stadium, Ahmedabad"

In [259]:
set(df["venue"])

{'Arun Jaitley Stadium, Delhi',
 'Barsapara Cricket Stadium, Guwahati',
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
 'Eden Gardens, Kolkata',
 'Himachal Pradesh Cricket Association Stadium, Dharamsala',
 'M Chinnaswamy Stadium, Bengaluru',
 'MA Chidambaram Stadium, Chepauk, Chennai',
 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
 'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh',
 'Narendra Modi Stadium, Ahmedabad',
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
 'Sawai Mansingh Stadium, Jaipur',
 'Wankhede Stadium, Mumbai'}

In [260]:
exact_venue_mapping = {
    'Arun Jaitley Stadium, Delhi': 'Arun Jaitley Stadium',
    'Barsapara Cricket Stadium, Guwahati': 'Barsapara Cricket Stadium',
    'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
    'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam': 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
    'Eden Gardens, Kolkata': 'Eden Gardens',
    'Himachal Pradesh Cricket Association Stadium, Dharamsala': 'Himachal Pradesh Cricket Association Stadium',
    'M Chinnaswamy Stadium, Bengaluru': 'M Chinnaswamy Stadium',
    'MA Chidambaram Stadium, Chepauk, Chennai': 'MA Chidambaram Stadium',
   
    'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur': 'Punjab Cricket Association IS Bindra Stadium',
    'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh': 'Punjab Cricket Association IS Bindra Stadium',
    
    'Narendra Modi Stadium, Ahmedabad': 'Narendra Modi Stadium',
    'Rajiv Gandhi International Stadium, Uppal, Hyderabad': 'Rajiv Gandhi International Stadium',
    'Sawai Mansingh Stadium, Jaipur': 'Sawai Mansingh Stadium',
    'Wankhede Stadium, Mumbai': 'Wankhede Stadium'
}

df['venue'] = df['venue'].replace(exact_venue_mapping)

In [261]:

known_teams = [
    'Kolkata Knight Riders', 'Kings XI Punjab', 'Lucknow Super Giants', 
    'Kochi Tuskers Kerala', 'Rising Pune Supergiants', 'Rising Pune Supergiant', 
    'Delhi Daredevils', 'Mumbai Indians', 'Gujarat Titans', 'Rajasthan Royals', 
    'Sunrisers Hyderabad', 'Royal Challengers Bangalore', 'Pune Warriors', 
    'Gujarat Lions', 'Delhi Capitals', 'Punjab Kings', 'Chennai Super Kings', 
    'Deccan Chargers'
]
team_mapping = {
    'Royal Challengers Bengaluru': 'Royal Challengers Bangalore'
}

df['batting_team'] = df['batting_team'].replace(team_mapping)
df['bowling_team'] = df['bowling_team'].replace(team_mapping)

# Quick verification check
print("Rogue Batting Teams:", set(df['batting_team']) - set(known_teams))
print("Rogue Bowling Teams:", set(df['bowling_team']) - set(known_teams))

Rogue Batting Teams: set()
Rogue Bowling Teams: set()

In [262]:
df

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,date,runs_scored,wickets_remaining,score,final_score,venue
0,1422119,1,0.1,0,1,Royal Challengers Bangalore,Chennai Super Kings,2024-03-22,1.0,10,1,173.0,MA Chidambaram Stadium
1,1422119,1,0.2,0,2,Royal Challengers Bangalore,Chennai Super Kings,2024-03-22,1.0,10,2,173.0,MA Chidambaram Stadium
2,1422119,1,0.3,0,3,Royal Challengers Bangalore,Chennai Super Kings,2024-03-22,0.0,10,2,173.0,MA Chidambaram Stadium
3,1422119,1,0.4,0,4,Royal Challengers Bangalore,Chennai Super Kings,2024-03-22,0.0,10,2,173.0,MA Chidambaram Stadium
4,1422119,1,0.5,0,5,Royal Challengers Bangalore,Chennai Super Kings,2024-03-22,0.0,10,2,173.0,MA Chidambaram Stadium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34383,1473511,2,19.2,19,2,Punjab Kings,Royal Challengers Bangalore,2025-06-03,0.0,3,162,184.0,Narendra Modi Stadium
34384,1473511,2,19.3,19,3,Punjab Kings,Royal Challengers Bangalore,2025-06-03,6.0,3,168,184.0,Narendra Modi Stadium
34385,1473511,2,19.4,19,4,Punjab Kings,Royal Challengers Bangalore,2025-06-03,4.0,3,172,184.0,Narendra Modi Stadium
34386,1473511,2,19.5,19,5,Punjab Kings,Royal Challengers Bangalore,2025-06-03,6.0,3,178,184.0,Narendra Modi Stadium
34387,1473511,2,19.6,19,6,Punjab Kings,Royal Challengers Bangalore,2025-06-03,6.0,3,184,184.0,Narendra Modi Stadium

In [263]:
import numpy as np
df['balls_bowled'] = (df['over'] * 6) + df['ball']
df['balls_remaining'] = np.clip(120 - df['balls_bowled'], 0, 120)
df['crr'] = (df['score'] * 6) / df['balls_bowled']
df['runs_last_5_overs'] = df.groupby(['matchId', 'inning'])['runs_scored'].rolling(window=30).sum().values
df = df[df['over'] >= 5].reset_index(drop=True)
df = df.rename(columns={'inning': 'innings'})

In [264]:
target_columns = [
    'venue', 
    'innings', 
    'batting_team', 
    'bowling_team', 
    'wickets_remaining', 
    'score', 
    'final_score', 
    'runs_last_5_overs', 
    'balls_remaining', 
    'crr'
]

df_final = df[target_columns]

print("Any null values left in the dataset?\n", df_final.isnull().sum())

Any null values left in the dataset?
 venue                  0
innings                0
batting_team           0
bowling_team           0
wickets_remaining      0
score                  0
final_score            0
runs_last_5_overs    176
balls_remaining        0
crr                    0
dtype: int64

In [265]:
df_final = df_final.dropna().reset_index(drop=True)
print(df_final.isnull().sum())

venue                0
innings              0
batting_team         0
bowling_team         0
wickets_remaining    0
score                0
final_score          0
runs_last_5_overs    0
balls_remaining      0
crr                  0
dtype: int64

In [266]:
df = df[["venue","innings","batting_team","bowling_team","wickets_remaining","score","final_score","runs_last_5_overs","balls_remaining","crr"]]

In [267]:
import pickle
def load_model():
    """Load the model only once to boost performance."""
    try:
        return pickle.load(open('model2.pkl', 'rb'))
    except FileNotFoundError:
        st.error("⚠️ Model file 'model2.pkl' not found. Please upload it to the directory.")
        return None

model3 = load_model()

In [268]:
from sklearn.model_selection import train_test_split
X=df.drop(columns=['final_score'])
y=df['final_score']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=42)

In [269]:
model3.fit(X_train,y_train)

/media/tst_imperial/Projects/IPL_SCORE_PREDICTOR/venv/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cltrf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team',
                                                   'venue'])])),
                ('step2', StandardScaler()),
                ('step3',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, device=N...
                              feature_types=None, gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.2,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=12, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=1500, n_jobs=None,
                              num_parallel_tree=None, random_state=1, ...))])

In [271]:
y_pred = model3.predict(X_test)

In [273]:
from sklearn.metrics import r2_score,mean_absolute_error
print("r2 score: ",r2_score(y_test,y_pred))
print("MEAN ABSOLUTE ERROR: ",mean_absolute_error(y_test,y_pred))

r2 score:  0.9941640051174151
MEAN ABSOLUTE ERROR:  1.2198958220305267

In [ ]:
pkl.dump(model3,open("model_.pkl","wb"))